## Numpy array and basics
learn about numpy


In [6]:
import numpy as np

### creating array from list

In [8]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


### List VS numpy array

In [11]:
py_list = [1,2,3]
print("Python List multiplication", py_list*2) #list replication

np_array = np.array([1,2,3]) #element-wise operations
print("Python Array multiplication", np_array*2)

import time
start = time.time()
py_list= [i*2 for i in range(1000000)]
print("\n Python List Time:", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("Numpy Array Time:", time.time() - start)

Python List multiplication [1, 2, 3, 1, 2, 3]
Python Array multiplication [2 4 6]

 Python List Time: 0.1096642017364502
Numpy Array Time: 0.008333921432495117


### creating array from scratch

In [21]:
zeros =np.zeros((3,4))
print("\nZeros Array:\n", zeros)

ones = np.ones((2,3))
print("\nOnes Array:\n", ones)

full = np.full((2,2), 7)
print("\nFull Array:\n", full)

random = np.random.random((2,3))
print("\nRandom Array:\n", random)

sequence  = np.arange(0, 10, 2)
print("\nSequence Array:\n", sequence)


Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Full Array:
 [[7 7]
 [7 7]]

Random Array:
 [[0.73600598 0.21664103 0.51080437]
 [0.29170356 0.104981   0.54386801]]

Sequence Array:
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [22]:
vector = np.array([1, 2, 3])
print("\nVector:", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMatrix:\n", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nTensor:\n", tensor)    


Vector: [1 2 3]

Matrix:
 [[1 2 3]
 [4 5 6]]

Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [27]:
arr = np.array([[1,2,3],[4,5,6]])
print("\nArray Shape:", arr.shape)
print("Array Dimensions:", arr.ndim)
print("Array Size:", arr.size)
print("Array Data Type:", arr.dtype)



Array Shape: (2, 3)
Array Dimensions: 2
Array Size: 6
Array Data Type: int64


### Array Reshaping

In [33]:
arr = np.arange(12)
print("\nOriginal Array:", arr)

reshaped = arr.reshape((3,4))
print("\nReshaped Array (3x4):\n", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array", flattened)

# revel ( returns view instead of copy)
reveled = reshaped.ravel()
print("\n Raveled array", reveled)

#Transpose
transposed = reshaped.T
print("\n Transposed Array:\n", transposed)


Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
